import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'

import './globals.css'

import Appbar from '~/components/shared/Appbar'
import Footer from '~/components/shared/Footer'

const maven = Maven_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={maven.className}>
        <Appbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
